# Generated by Django 4.1.4 on 2022-12-30 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('emails', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='_id',
            new_name='id',
        ),
        migrations.RenameField(
            model_name='profile',
            old_name='_id',
            new_name='id',
        ),
    ]
